/**
 * Multi-boot support — put multiple ISOs on one USB drive.
 * Inspired by Ventoy: GRUB-based boot menu, no re-flash needed.
 */

import * as fs from 'fs';
import * as path from 'path';

export interface BootEntry {
  id: string;
  name: string;
  isoPath: string;
  isoSize: number;
  type: 'linux' | 'windows' | 'utility' | 'other';
  addedAt: number;
}

export interface MultiBoot {
  version: number;
  entries: BootEntry[];
  totalSize: number;
  driveSize: number;
  freeSpace: number;
}

export function createBootEntryId(): string {
  return `boot-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
}

export function detectImageType(filename: string): BootEntry['type'] {
  const lower = filename.toLowerCase();
  if (/win(dows|10|11|8|7)|server.?(2019|2022)/.test(lower)) return 'windows';
  if (/ubuntu|fedora|debian|arch|mint|kali|centos|suse|manjaro|pop.?os|elementary|tails|zorin/.test(lower)) return 'linux';
  if (/memtest|gparted|clonezilla|hiren|medicat|ventoy|grub/.test(lower)) return 'utility';
  return 'other';
}

export function canAddImage(driveSize: number, usedSpace: number, imageSize: number, reservedMB = 100): boolean {
  const reserved = reservedMB * 1024 * 1024;
  return (usedSpace + imageSize + reserved) <= driveSize;
}

export function generateGrubEntry(entry: BootEntry): string {
  const isoFile = path.basename(entry.isoPath);

  if (entry.type === 'linux') {
    return `
menuentry "${entry.name}" {
    set isofile="/images/${isoFile}"
    loopback loop \$isofile
    linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=\$isofile quiet splash
    initrd (loop)/casper/initrd
}`.trim();
  }

  if (entry.type === 'windows') {
    return `
menuentry "${entry.name}" {
    set isofile="/images/${isoFile}"
    loopback loop \$isofile
    chainloader (loop)/efi/boot/bootx64.efi
}`.trim();
  }

  return `
menuentry "${entry.name}" {
    set isofile="/images/${isoFile}"
    loopback loop \$isofile
    chainloader (loop)+1
}`.trim();
}

export function generateGrubConfig(entries: BootEntry[]): string {
  const header = `# Spark Multi-Boot Configuration
# Generated by Spark Flash Tool

set timeout=10
set default=0

insmod all_video
insmod gfxterm
set gfxmode=auto
terminal_output gfxterm

menuentry "Boot from hard disk" {
    chainloader +1
}
`;

  const menuEntries = entries.map(generateGrubEntry).join('\n\n');
  return header + '\n' + menuEntries + '\n';
}

export function estimateMultiBootOverhead(): number {
  // GRUB bootloader + config + fonts ≈ 15 MB
  return 15 * 1024 * 1024;
}
